# Generated by Django 5.2.3 on 2025-06-20 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QuestionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="CSS class for icon", max_length=50
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Question Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("answer", models.TextField()),
                (
                    "explanation",
                    models.TextField(
                        blank=True, help_text="Detailed explanation of the answer"
                    ),
                ),
                (
                    "code_example",
                    models.TextField(
                        blank=True, help_text="Code example if applicable"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("conceptual", "Conceptual"),
                            ("coding", "Coding"),
                            ("system_design", "System Design"),
                            ("math", "Mathematics"),
                            ("case_study", "Case Study"),
                        ],
                        default="conceptual",
                        max_length=20,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=500
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="question_answer.questioncategory",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "order", "question_text"],
                "unique_together": {("category", "slug")},
            },
        ),
    ]
